### ISSUE TITLE
authCode is changed

### ISSUE THREAD

**Issue by wouter075** [simplyGits/MagisterJS#108]
The authCode is changed as of 9.20 (CET), the new code for us is: `c39f6a`

**Comment by gruijter** [comment]
So what does this mean? Do we need to change the auth code every day now? Can this be changed automatically?

**Comment by Sj3rd** [comment]
See: https://github.com/simplyGits/MagisterJS/issues/110

**Comment by lieuwex** [comment]
The latter, basically whenever you're now creating a new magister object using [`magister`](https://doc.esdoc.org/github.com/simplyGits/MagisterJS/function/index.html#static-function-magister). You should provide an `authCode`, if none is given it will be retrieved from the `@magisterjs/authcode` package.

**Comment by gruijter** [comment]
Clear. Thx!

**Comment by Sj3rd** [comment]
But if you want to have the up to date code, make sure to update your package every couple days. Or provide the code yourself from an get request to https://raw.githubusercontent.com/simplyGits/magisterjs-authcode/master/code.json

**Comment by gruijter** [comment]
I implemented this, works ok. I create a session every hour to fetch grades, appointments, etc. Before each session I fetch the authcode from internet.
Question: if I login with token, do I still need the authcode also? And how is the authcode updated on the internet? Is that automatic, or does it require manual action by someone? Im asking because in my Homey app, the students can let there alarm go off based on the first schoolhour. If the authcode changes at midnight, how soon will I be able to fetch the correct code? The students alarm will not go off on time if my app fails to login after midnight😴

**Comment by lieuwex** [comment]
> if I login with token, do I still need the authcode also? 

As far as I know, no. You should be fine.

> And how is the authcode updated on the internet? Is that automatic, or does it require manual action by someone?

Roughly every hour a script is ran on my server which checks if the authcode has been changed, and if it has, it will publish the new code online. It also runs during the night.

P.S.

FWIW, if you are dynamically fetching the authcode: I've created a package which should aid in doing that. It will fallback on the package contents, so it should be as safe as possible to use:
```javascript
const getAuthCode = require('@magisterjs/dynamic-authcode');
const authCode = await getAuthCode();
```

**Comment by gruijter** [comment]
> Roughly every hour a script is ran on my server which checks if the authcode has been changed, and if it has, it will publish the new code online. It also runs during the night.

Apparently the authcode changed again yesterday around 4pm. I know this because of my logs, and because I get a lot of issues reported by users of my app :(

I fetch the authcode ever hour from `https://raw.githubusercontent.com/simplyGits/magisterjs-authcode/master/code.json` , but it took untill 7am this morning before I could login again. So if you publish the new code within an hour, how can it take around 15 hours before the login works again? Do I need to do something different to make it work faster?

**Comment by Argetan** [comment]
Something went wrong with the script that is supposed to update the code. See [#2](https://github.com/simplyGits/magisterjs-authcode/issues/2) on the `magisterjs-authcode` repository.

**Comment by gruijter** [comment]
Is there a way to run the script from the magister.js module itself? Now the login functionality is dependent on external scripts running on someone's computer, and online access to a hosted page.

**Comment by Argetan** [comment]
I don't think it is, but you'd have to ask @lieuwex to be sure. What I'm guessing is that SchoolMaster sends the code to @lieuwex who then let's the automated script upload it to `magisterjs-authcode` repository. The most reliable way for you to fetch the authentication code is through an HTTP request or use the `dynamic-authcode` bundled with `magister.js`, as that will get the latest version of the code from GitHub.

There is an official API (through web requests), `magister.js` functions as an interface to automate the requests. The only documentation I could find on the API are the [terms of use](https://www.magister.nl/gebruiksvoorwaarden-api/) (Dutch). There also is an interface for the API written in PHP, which can be found [here](https://github.com/magister-api/magister).

**Comment by gruijter** [comment]
@lieuwex Anything you can share on ^ topic? Would it be possible to somehow get the authcode directly  without fetching from an external site that is dependent on the server under your bed?
Would Magister be willing to officially support users of magister.js, and provide the authcode directly somehow?
Or would it be possible to do a completely different authorization based on the student/parent oAuth login (apparently this is what the magister app uses)?

**Comment by gruijter** [comment]
Wow. This wouldnt run on a headless arm bases system I think. Puppeteer needs Chrome it sais in the docs...

**Comment by lieuwex** [comment]
> What I'm guessing is that SchoolMaster sends the code to @lieuwex who then let's the automated script upload it to magisterjs-authcode repository. 

Nope, the script just behaves like a normal user would, and then sniffs the network requests and extracts the authcode.

> Would Magister be willing to officially support users of magister.js, and provide the authcode directly somehow?

I doubt it since they're pretty hostile to me in the past, but of course you can ask them yourself.

> Or would it be possible to do a completely different authorization based on the student/parent oAuth login (apparently this is what the magister app uses)?

I think we would have the same problems as we have now, in that case.

> Apparently the authcode changed again yesterday around 4pm.

My script is still a bit hacky, but I feel like it should work now :P

> Is there a way to run the script from the magister.js module itself? 

The script given by @Sj3rd is nice! Which is pretty much the best thing you can do if you want to directly fetch the authcode yourself. But if your plan is to run this on a Homey, I don't think that's possible (figuring they have _some_ security in place).

> This wouldnt run on a headless arm bases system I think.

Well that should work, the chromium instance _is_ headless and should run on ARM. But the security aspect is something I'm afraid of :P

**Comment by Sj3rd** [comment]
> Wow. This wouldnt run on a headless arm bases system I think. Puppeteer needs Chrome it sais in the docs...

Im running it on a headless linux arm system. Just make sure a headless version of chrome is installed :)
