### ISSUE TITLE
Magister.ready() does not log in

### ISSUE THREAD

**Issue by IsaiahvH** [simplyGits/MagisterJS#12]
Hello!

I tried the sample code on your TryOut page, but `m` is `undefined`.
The following is the code I have used:
```javascript
new Magister("Dalton Den Haag", "<username>", "<password>").ready(function (m) {
    console.log(m);
    alert("Hey, " + m.profileInfo().firstName() + "!");
});
```
`console.log(m);` returns `undefined` in the developer console, and the `alert()` returns `Uncaught TypeError: Cannot read property 'profileInfo' of undefined` as error.
Of course, the `<username>` and `<password>` are replaced correctly, and I also tried `{ url: "https://daltondenhaag.magister.net" }` instead of the string, although I checked https://mijn.magister.net/api/schools?filter=Dalton, and `Dalton Den Haag` is definitely there.

Also, Magister is online and the login credentials given do work when I login on Magister 6 itself.

I tested this in Google Chrome (41.0.2272.43) and Safari (8.0.3) on Mac OS X Yosemite (10.10.2).
What can be done to fix this problem?

Thanks in advance,

Isaiah van Hunen

*I tried the code above before, I think, and at the time it worked.
(Is the circumvention for the same-origin policy still working?)*

**Comment by lieuwex** [comment]
Hey Isaiah!

In commit b17c393f070162d4a6e44fd98ac4069c6bbedb84 I changed the way `Magister.ready()` worked.
I didn't update the docs and examples, which is just plain stupid... I'm so sorry since you really tried to help us with the detailed info, which I really appreciate.

In short, the new code should be:
```JavaScript
new Magister("Dalton Den Haag", "<username>", "<password>").ready(function (err) {
    console.log(this);
    alert("Hey, " + this.profileInfo().firstName() + "!");
});
```

`err` contains an error, if any.

I will update the docs and default code in the TryOut, thanks for the heads up, and sorry once again.

-Lieuwe Rooijakkers

**Comment by IsaiahvH** [comment]
Hi,

No, don't worry!
I actually appreciate the fast and kind response immensely.
It's working now.

Thanks again!
