### ISSUE TITLE
SECURITY ISSUE: Browser version is susceptible to man-in-the-middle vector.

### ISSUE THREAD

**Issue by CharString** [simplyGits/MagisterJS#41]
Since node.js as always advertised as "just javascript" I was expecting the browser try out to run in my browser and directly do requests to magister.net. Instead it posts requests to simplyapps.nl (running at heroku).

I have 2 grave issues with this:

1. it doesn't use TLS, so it is susceptible to man-in-the-middle-attacks. Magister user data contains private data like names, birthdates, addresses etc. So stolen credentials matter!
2. this turns simplyapps.nl (and heroku) into a man-in-the-middle, giving it the ability to log all credentials. There is no guarantee that simplyapps aren't using stolen credentials to get street-cred at his high-school, nor that heroku isn't selling the data to pay for all the free server time they give away.

Other than this: nice project! :-)

**Comment by lieuwex** [comment]
Hey Chris,

Thanks for your report. We can't send the data directly from the browser to Magister since they don't have [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) enabled, so we need some sort of proxy.

I agree with your concern of not having TLS here, I might get a certificate for the try-out, from something like Let’s Encrypt.

On your second point, I understand your concern, but as I said there isn't really a way to send data directly from the browser. I think it's a matter of trust, I [open-sourced](https://github.com/lieuwex/SmallProxy) the code that's running on the heroku instance, but that of course doesn't really mean anything.
I guess the best thing to do is to show a warning which tells that unecrypted (for now at least) data is sent to our server. What do you think? (and @simplyGits/simplycoders?)

Thanks! :)

**Comment by tkon99** [comment]
Well, tbh I don't see the use of the try out anyway. For me it doesn't really add anything to the usual code examples. Perhaps we should include those in the readme? (@lieuwex)

We can't really prove we haven't edited the code further than we already do by making it open source.
We could of course make a chrome extension which acts like a proxy. (iirc)

**Comment by lieuwex** [comment]
@tkon99 magister.js v2 will no longer have a browser-side and I had the idea of linking [Tonic](https://tonicdev.com/npm/magister.js) instead of our try-out. It does solve point 1 but not point 2, though.

We could also remove the try-out completely indeed.

**Comment by lesander** [comment]
My two cents on this: Heroku deploys TLS and SSL certificates for all `*.herokuapp.com` subdomains. So https://smallproxy.herokuapp.com/ actually is secure. You can also automatically deploy GitHub repositories to Heroku with hooks, but of course there always needs to be good faith in the developers.

**Comment by lieuwex** [comment]
Thanks @lesander I have switched the tryout to connect using https in 57ef332843c34767c301f699197f78cabe1d9395.

**Comment by lesander** [comment]
No problem @lieuwex, glad to help :smile:

**Comment by CharString** [comment]
That at least brings it down to trusting simplyapps and heroku (and all CA's :-)), instead of the whole network.

> I think it's a matter of trust, I open-sourced the code that's running on the heroku instance, but that of course doesn't really mean anything.

Open-sourcing it means the world to me. It doesn't make the browser version secure to use. But it does allow us to study the code and use it on machines we do trust. I do still think a warning is the right thing to do. Full disclosure will allow each user to make their own, informed decision. I for one wasn't amused when I opened op the code after trying it out and found out the route my credentials had taken.
