### ISSUE TITLE
When will V2 be released to npm

### ISSUE THREAD

**Issue by dannykruitbosch** [simplyGits/MagisterJS#63]
Hi,

Thanks for putting this together. I just have a quick question, when will v2 be released to NPM?

Thanks,

Danny

**Comment by lieuwex** [comment]
I have no idea, the functionality is currently lacking, I will work on magister.js when I have a little more time. But feel free to contribute yourself on the v2 branch. :)

The big thing that still has to be finished is grades, but I want to clearly think out a good way to structure them since it a disaster in v1.

Hope this answers your question.
